### ISSUE TITLE
Tab buttons don't work when Remote JS Debugging is running

### ISSUE THREAD

**Issue by akhila-ariyachandra** [react-native-community/react-native-tab-view#669]
### Current behaviour

The tab buttons stop working when using Remote JS Debugging is running, even though swiping works fine. The tab buttons work when Remote JS Debugging is not running.

### Expected behaviour

The tabs should switch when the button is pressed even when Remote JS Debugging is running.

### Code sample

```
import * as React from 'react';
import {TabView, TabBar, SceneMap} from 'react-native-tab-view';
import Discover from './DiscoverTab';
import Create from './CreateTab';
import Manage from './ManageTab';
import Alerts from './AlertsTab';
import {Text} from 'react-native-paper';

/**
 * Root component to hold all the tabs in the Home screen
 */
export default class HomeScreen extends React.PureComponent {
  /**
   * @param {object} props
   * @return {void}
   */
  constructor(props) {
    super(props);
    this.state = {
      index: 0,
      routes: [
        {key: 'discover', title: 'Discover'},
        {key: 'create', title: 'Create'},
        {key: 'manage', title: 'Manage'},
        {key: 'alerts', title: 'Alerts'},
      ],
    };
  }

  // eslint-disable-next-line new-cap
  _renderScene = SceneMap({
    discover: Discover,
    create: Create,
    manage: Manage,
    alerts: Alerts,
  });

  /**
   * @param {object} props
   * @return {JSX.Element}
   */
  _renderTabBar = (props) => {
    const renderLabel = (props) => {
      let index = 0;
      return ({route}) => {
        const focused = index === props.navigationState.index;
        index += 1;

        // Don't show label for Create tab
        if (route.key === 'create') {
          return (null);
        } else {
          return (
            <Text style={{color: (focused) ? 'blue' : 'grey'}}>{route.title}</Text>
          );
        }
      };
    };

    return (
      <TabBar
        {...props}
        renderLabel={renderLabel(props)}
        style={{backgroundColor: 'white'}}
        indicatorStyle={{backgroundColor: 'grey'}}
      />
    );
  }

  /**
   * @param {number} index
   * @return {void}
   */
  _handleIndexChange = (index) => {
    return this.setState({index});
  }

  /**
   * @return {JSX.Element}
   */
  render = () => (
    <TabView
      navigationState={this.state}
      renderScene={this._renderScene}
      renderTabBar={this._renderTabBar}
      tabBarPosition='bottom'
      onIndexChange={this._handleIndexChange}
    />
  )
}

```
### What have you tried

Switching to v1.0.2 of the library fixed the issue.

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | android
| react-native          | 0.57.8
| react-native-tab-view | 1.3.1
| node                  | 11.6.0
| npm or yarn           | npm

**Comment by steoo** [comment]
+1

**Comment by satya164** [comment]
Hey, I just released a new alpha `2.0.0-alpha.0` of the library. It's rewritten using [react-native-gesture-handler](https://github.com/kmagiera/react-native-gesture-handler) and [react-native-reanimated](https://github.com/kmagiera/react-native-reanimated) addresses a many platform specific bugs and performance problems. The documentation is updated as well.

Please try the new version and see if it addresses your issue. If not, please open a new issue following the issue template.

**Comment by akhila-ariyachandra** [comment]
No luck with version 2.0.0-alpha.1. Tab switching doesn't work with the debugger on. With it off there's a noticeable delay when switching tabs.

**Comment by nkulic** [comment]
> No luck with version 2.0.0-alpha.1. Tab switching doesn't work with the debugger on. With it off there's a noticeable delay when switching tabs.

Did anything changed? I've used last version today and run across this same issue. I went to try with debugging but unsuccessfully because with debugger enabled switching tabs does not work

**Comment by jean-marc-cp** [comment]
I'm still seeing this in 2.15.2 If you have swiping turned on that works when debugging is enabled though.
